// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrpx43I5fY7nKi15riQfH7tu9inQJkAE',
    appId: '1:269349308702:web:7dbcd69006470b64cda10f',
    messagingSenderId: '269349308702',
    projectId: 'drivedoctor-ea7d6',
    authDomain: 'drivedoctor-ea7d6.firebaseapp.com',
    storageBucket: 'drivedoctor-ea7d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDATF3xN5gOaZrJu5E0DAu5haWN54cnpE4',
    appId: '1:269349308702:android:b09f1e9feb054eb4cda10f',
    messagingSenderId: '269349308702',
    projectId: 'drivedoctor-ea7d6',
    storageBucket: 'drivedoctor-ea7d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMEhC-HVtokRHXbnR33kZpcjnzGgfU3Sg',
    appId: '1:269349308702:ios:cc5ace3950ae357dcda10f',
    messagingSenderId: '269349308702',
    projectId: 'drivedoctor-ea7d6',
    storageBucket: 'drivedoctor-ea7d6.appspot.com',
    iosClientId: '269349308702-aug51rpe1r9c4ikj374k3hslr7gmmgqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivedoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMEhC-HVtokRHXbnR33kZpcjnzGgfU3Sg',
    appId: '1:269349308702:ios:cc5ace3950ae357dcda10f',
    messagingSenderId: '269349308702',
    projectId: 'drivedoctor-ea7d6',
    storageBucket: 'drivedoctor-ea7d6.appspot.com',
    iosClientId: '269349308702-aug51rpe1r9c4ikj374k3hslr7gmmgqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivedoctor',
  );
}
