import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:drivedoctor/bloc/models/shop.dart';

class ProductData {
  final String productId; // Document ID generated by Firebase
  final String productName;
  final String description;
  final double price;
  String? imageUrl;
  final String shopId; // Reference to the shop's document ID
  double rating;
  int stock;
  int totalSold;
  ShopData? shop; // Add ShopData reference

  ProductData({
    required this.productId,
    required this.productName,
    required this.description,
    required this.price,
    this.imageUrl,
    required this.shopId,
    this.rating = 5,
    this.stock = 0,
    this.totalSold = 0,
    this.shop, // Provide optional ShopData reference in the constructor
  });

  factory ProductData.fromSnapshot(DocumentSnapshot snapshot) {
    final data = snapshot.data() as Map<String, dynamic>;

    return ProductData(
      productId: snapshot.id, // Store the document ID as productId
      productName: data['productName'],
      description: data['description'] ?? "-",
      price: data['price'],
      imageUrl: data['imageUrl'],
      shopId: data['shopId'],
      rating: data['rating'] ?? 5,
      stock: data['stock'] ?? 0,
      totalSold: data['totalSold'] ?? 0,
    );
  }

  //toJson
  Map<String, dynamic> toJson() {
    return {
      'productId': productId,
      'productName': productName,
      'description': description,
      'price': price,
      'imageUrl': imageUrl,
      'shopId': shopId,
      'rating': rating,
      'stock': stock,
      'totalSold': totalSold,
    };
  }

  //fromJson
  factory ProductData.fromJson(Map<String, dynamic> json) {
    return ProductData(
      productId: json['productId'],
      productName: json['productName'],
      description: json['description'],
      price: json['price'],
      imageUrl: json['imageUrl'],
      shopId: json['shopId'],
      rating: json['rating'],
      stock: json['stock'],
      totalSold: json['totalSold'],
    );
  }
}
